<?php
// This file is part of Moodle - https://moodle.org/

/**
 * Hook callbacks for the Feedback Dashboard plugin.
 *
 * @package    local_feedbackdashboard
 * @copyright  2026 Marcus Vinícius Milan da Silva
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_feedbackdashboard\local;

defined('MOODLE_INTERNAL') || die();

/**
 * Feedback Dashboard hook callbacks.
 */
class hook_callbacks {

    /**
     * Adds the Dashboard NPS button beside Moodle's native
     * "Exportar para o Excel" button on Feedback analysis.php.
     *
     * @param \core\hook\output\before_standard_top_of_body_html_generation $hook
     * @return void
     */
    public static function add_analysis_dashboard_button(
        \core\hook\output\before_standard_top_of_body_html_generation $hook
    ): void {
        global $OUTPUT, $PAGE, $SCRIPT;

        /*
         * Execute only on:
         *
         * /mod/feedback/analysis.php
         */
        if ($SCRIPT !== '/mod/feedback/analysis.php') {
            return;
        }

        /*
         * Must belong to a course module.
         */
        if (empty($PAGE->cm)) {
            return;
        }

        /*
         * Only native Moodle Feedback activities.
         */
        if ($PAGE->cm->modname !== 'feedback') {
            return;
        }

        $context = \context_module::instance(
            $PAGE->cm->id
        );

        /*
         * Same report permission used by Feedback itself.
         */
        if (
            !has_capability(
                'mod/feedback:viewreports',
                $context
            )
        ) {
            return;
        }

        /*
         * Our plugin-specific permission.
         */
        if (
            !has_capability(
                'local/feedbackdashboard:view',
                $context
            )
        ) {
            return;
        }

        /*
         * Dashboard of the CURRENT Feedback.
         *
         * analysis.php?id=7
         *
         * becomes:
         *
         * /local/feedbackdashboard/index.php?id=7
         */
        $dashboardurl = new \moodle_url(
            '/local/feedbackdashboard/index.php',
            [
                'id' => $PAGE->cm->id,
            ]
        );

        /*
         * IMPORTANT:
         *
         * Generate the button using Moodle's OWN single_button()
         * renderer.
         *
         * Therefore the button receives exactly the same Moodle/
         * Bootstrap structure as "Exportar para o Excel".
         */
        $nativebutton = $OUTPUT->single_button(
            $dashboardurl,
            'Dashboard NPS',
            'get'
        );

        /*
         * Source container.
         *
         * It starts hidden because it will be moved beside the
         * native Excel button after analysis.php finishes rendering.
         */
        $html = \html_writer::div(
            $nativebutton,
            '',
            [
                'id' => 'feedbackdashboard-button-source',
                'style' => 'display:none;',
            ]
        );

        /*
         * JavaScript moves the Moodle-generated button into:
         *
         * <div class="form-buttons">
         *
         * which is exactly where mod_feedback/analysis.php places
         * "Exportar para o Excel".
         */
        $html .= <<<'HTML'
<script>
(function() {
    'use strict';

    function moveFeedbackDashboardButton() {

        /*
         * Button generated by Moodle itself.
         */
        const source = document.getElementById(
            'feedbackdashboard-button-source'
        );

        if (!source) {
            return false;
        }

        /*
         * Native Feedback Analysis action area.
         */
        const target = document.querySelector(
            '.form-buttons'
        );

        if (!target) {
            return false;
        }

        /*
         * Do not insert twice.
         */
        if (
            target.querySelector(
                '[data-feedbackdashboard-button="1"]'
            )
        ) {
            source.remove();

            return true;
        }

        /*
         * $OUTPUT->single_button() produces a .singlebutton wrapper.
         */
        const buttonwrapper = source.querySelector(
            '.singlebutton'
        );

        /*
         * Fallback in case the theme changes the wrapper.
         */
        const element = buttonwrapper ||
            source.firstElementChild;

        if (!element) {
            return false;
        }

        /*
         * Mark our Moodle-generated button.
         */
        element.setAttribute(
            'data-feedbackdashboard-button',
            '1'
        );

        /*
         * Keep both native actions in the same row.
         */
        target.style.display = 'flex';
        target.style.alignItems = 'center';
        target.style.flexWrap = 'wrap';
        target.style.gap = '0.5rem';

        /*
         * Move Dashboard NPS directly after Exportar para o Excel.
         */
        target.appendChild(element);

        /*
         * Remove the now-empty hidden source.
         */
        source.remove();

        return true;
    }

    function initialiseFeedbackDashboardButton() {

        /*
         * First attempt.
         */
        if (moveFeedbackDashboardButton()) {
            return;
        }

        /*
         * analysis.php may not yet have rendered .form-buttons.
         *
         * Observe the DOM until Moodle creates it.
         */
        const observer = new MutationObserver(
            function() {
                if (moveFeedbackDashboardButton()) {
                    observer.disconnect();
                }
            }
        );

        observer.observe(
            document.documentElement,
            {
                childList: true,
                subtree: true
            }
        );

        /*
         * Do not observe forever.
         */
        window.setTimeout(
            function() {
                observer.disconnect();
            },
            15000
        );
    }

    if (document.readyState === 'loading') {

        document.addEventListener(
            'DOMContentLoaded',
            initialiseFeedbackDashboardButton,
            {
                once: true
            }
        );

    } else {

        initialiseFeedbackDashboardButton();

    }

})();
</script>
HTML;

        /*
         * Send everything through the official Moodle output hook.
         */
        $hook->add_html($html);
    }
}